### ISSUE TITLE
make-local-texmf is damaged and cannot be opened

### ISSUE THREAD

**Issue by rzambre** [amunn/make-local-texmf#1]
I am running MacOS Mojave 10.14.3. Any workarounds?

[Screen Shot 2019-02-20 at 9.22.41 PM.pdf](https://github.com/amunn/make-local-texmf/files/2887514/Screen.Shot.2019-02-20.at.9.22.41.PM.pdf)

**Comment by amunn** [comment]
Hi thanks for the bug report. I don't have Mojave running on any of my machines at the moment, but I'll see what I can do.  In the meantime, you could run the `makelocaltexmf.sh` file directly from the Terminal and avoid the app completely.

**Comment by amunn** [comment]
Fixed with properly signed code.
